// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Troca_Comigo_GS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113215149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("SEQ_AVALIACOES", "RM556834");

            modelBuilder.HasSequence("SEQ_HABILIDADES", "RM556834");

            modelBuilder.HasSequence("SEQ_TRANSACOES", "RM556834");

            modelBuilder.HasSequence("SEQ_TROCAS", "RM556834");

            modelBuilder.HasSequence("SEQ_USUARIOS", "RM556834");

            modelBuilder.Entity("Domain.Entities.Avaliacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AvaliadoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("AVALIADO_ID");

                    b.Property<Guid>("AvaliadorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("AVALIADOR_ID");

                    b.Property<string>("Comentario")
                        .HasColumnType("VARCHAR(2000)")
                        .HasColumnName("COMENTARIO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTA");

                    b.Property<Guid>("TrocaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("TROCA_ID");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadoId");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("TrocaId");

                    b.ToTable("AVALIACOES");
                });

            modelBuilder.Entity("Domain.Entities.Habilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CATEGORIA");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("DESCRICAO");

                    b.Property<bool>("IsOffering")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("OFERECE");

                    b.Property<bool>("IsSeeking")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("PROCURA");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("NIVEL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NOME");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("USUARIO_ID");

                    b.Property<double?>("ValorPorHora")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VALOR_HORA");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HABILIDADES");
                });

            modelBuilder.Entity("Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<double>("Creditos")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CREDITOS");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Descricao")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("DESTINATARIO_ID");

                    b.Property<Guid>("RemetenteId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("REMETENTE_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("TIPO");

                    b.Property<Guid?>("TrocaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("TROCA_ID");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("RemetenteId");

                    b.HasIndex("TrocaId");

                    b.ToTable("TRANSACOES");
                });

            modelBuilder.Entity("Domain.Entities.Troca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ALUNO_ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<double?>("CreditsValue")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CREDITOS");

                    b.Property<double>("DurationHours")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("DURACAO_HORAS");

                    b.Property<Guid>("HabilidadeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("HABILIDADE_ID");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("MEETING_LINK");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("MENTOR_ID");

                    b.Property<string>("Notes")
                        .HasColumnType("VARCHAR(2000)")
                        .HasColumnName("NOTAS");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_AGENDADA");

                    b.Property<string>("SkillName")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NOME_HABILIDADE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("STATUS_TROCA");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("HabilidadeId");

                    b.HasIndex("MentorId");

                    b.ToTable("TROCAS");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("AVATAR_URL");

                    b.Property<double>("AverageRating")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("MEDIA_AVALIACOES");

                    b.Property<string>("Bio")
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("BIO");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NOME_COMPLETO");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LINKEDIN_URL");

                    b.Property<string>("Location")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("LOCALIZACAO");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("ROLE");

                    b.Property<double>("TimeCredits")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CREDITOS_TEMPO");

                    b.Property<string>("Timezone")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("TIMEZONE");

                    b.Property<int>("TotalSessionsGiven")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_SESSOES_DADAS");

                    b.Property<int>("TotalSessionsTaken")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTAL_SESSOES_RECEBIDAS");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.HasKey("Id");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("UsuarioUsuario", b =>
                {
                    b.Property<Guid>("Usuario1Id")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Usuario1Id", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioUsuario");
                });

            modelBuilder.Entity("Domain.Entities.Avaliacao", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Avaliado")
                        .WithMany("AvaliacoesRecebidas")
                        .HasForeignKey("AvaliadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Avaliador")
                        .WithMany("AvaliacoesFeitas")
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Troca", "Troca")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("TrocaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliado");

                    b.Navigation("Avaliador");

                    b.Navigation("Troca");
                });

            modelBuilder.Entity("Domain.Entities.Habilidade", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Habilidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Transacao", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Troca", "Troca")
                        .WithMany("Transacoes")
                        .HasForeignKey("TrocaId");

                    b.Navigation("Destinatario");

                    b.Navigation("Remetente");

                    b.Navigation("Troca");
                });

            modelBuilder.Entity("Domain.Entities.Troca", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Aluno")
                        .WithMany("TrocasComoAluno")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Mentor")
                        .WithMany("TrocasComoMentor")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Habilidade");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("UsuarioUsuario", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("Usuario1Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Troca", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AvaliacoesFeitas");

                    b.Navigation("AvaliacoesRecebidas");

                    b.Navigation("Habilidades");

                    b.Navigation("TrocasComoAluno");

                    b.Navigation("TrocasComoMentor");
                });
#pragma warning restore 612, 618
        }
    }
}
